---
title: "kendel tests"
author: "Faith Jones"
date: "30 June 2017"
output: html_document
---

```{r}
setwd("C:\\Users\\faj\\Documents\\OneDrive for Business\\research\\FishPredation\\Data")

library(dplyr)
library(tidyr)
library(ggplot2)
library(vegan)

fishDataAll <- read.csv("Fish data June 2017.csv")

#preparing data 

head(fishDataAll)
str(fishDataAll)
levels(fishDataAll$species)
selectMonths <- c("07", "08")# i am selecting out these months because then i can use the last timepoint 

#select data from only the July and Auguest, and remove first year 
SelectData <- fishDataAll %>% 
	separate(date, c("Day", "Month", "Year"), sep = "/") %>%
	filter(Year != 2010)%>%
	filter(Month %in% selectMonths)

fishData <- data.frame(SelectData)


```

##Biomass - three levels of predation definition
I have run a kendal concordance test on each set of the data, using a function from
the vegan package. see below. Sites are more similarly ranked each year using the 
narrow predation (W = 0.6) then the middle (0.3) or wide (0.3) definition. 

```{r}

##Anylise Biomass of the two main predators of guppies. Narrow view of predation 
#-----------------------------------------------------------------------------------

#sum biomass per site and year
predatorsBioN <- fishData %>% 
	filter(species == "Hoplias malabaricus" | species == "Crenicichla frenata") %>%
	group_by(site, Year) %>%
	summarise(BiomassSum = sum(weight)) %>%
	spread(Year, BiomassSum)

predatorsBio <- data.frame(predatorsBioN)

predatorsBio[is.na(predatorsBio)] <- 0 
colnames(predatorsBio)[c(2:7)] <- c("2010", "2011", "2012", "2013", "2014", "2015")

predatorsBio

kendall.global(predatorsBio)

```


```{r}
##Anylise Biomass of the two main predators of guppies. Middle view of predation 
#-----------------------------------------------------------------------------------

#sum biomass per site and year
predatorsBioM <- fishData %>% 
	filter(species == "Hoplias malabaricus" | species == "Crenicichla frenata" | 
		species == "Gymnotus carapo"| species == "Anablepsoides hartii") %>%
	group_by(site, Year) %>%
	summarise(BiomassSum = sum(weight)) %>%
	spread(Year, BiomassSum)


mPredatorsBio <- data.frame(predatorsBioM)

mPredatorsBio[is.na(mPredatorsBio)] <- 0 
colnames(mPredatorsBio)[c(2:7)] <- c("2010", "2011", "2012", "2013", "2014", "2015")

mPredatorsBio

kendall.global(mPredatorsBio)

```


```{r}
##Anylise Biomass of the two main predators of guppies. Wide view of predation 
#-----------------------------------------------------------------------------------

group12 <- c("Hoplias malabaricus", "Crenicichla frenata", "Gymnotus carapo", "Anablepsoides hartii",
			"Cichlasoma taenia", "Cichlasoma taenia", "Corynopoma riisei", "Roeboides dientonito", 
			"Agonostomus monticola", "Rhamdia quelen", "andinoacara pulcher", "Hemigrammus unilineatus")


#sum biomass per site and year
predatorsBioW <- fishData %>% 
	filter(species %in% group12) %>%
	group_by(site, Year) %>%
	summarise(BiomassSum = sum(weight)) %>%
	spread(Year, BiomassSum)

wPredatorsBio <- data.frame(predatorsBioW)
wPredatorsBio[is.na(wPredatorsBio)] <- 0 
colnames(wPredatorsBio)[c(2:7)] <- c("2010", "2011", "2012", "2013", "2014", "2015")

wPredatorsBio

kendall.global(wPredatorsBio)

```


