---
title: "Kendall Abundance"
author: "Faith Jones"
date: "30 June 2017"
output: html_document
---
```{r}
setwd("C:\\Users\\faj\\Documents\\OneDrive for Business\\research\\FishPredation\\Data")

library(dplyr)
library(tidyr)
library(ggplot2)
library(vegan)

fishDataAll <- read.csv("Fish data June 2017.csv")

#preparing data 

head(fishDataAll)
str(fishDataAll)
levels(fishDataAll$species)
selectMonths <- c("07", "08")# i am selecting out these months because then i can use the last timepoint 

#select data from only the July and Auguest, and remove first year 
SelectData <- fishDataAll %>% 
	separate(date, c("Day", "Month", "Year"), sep = "/") %>%
	filter(Year != 2010)%>%
	filter(Month %in% selectMonths)

fishData <- data.frame(SelectData)

fishData$AbundanceAll <- fishData$numbercaught + fishData$numberseen

```

##Abundance - three levels of predation definition
I have run a kendal concordance test on each set of the data, using a function from
the vegan package. see below. Sites are more similarly ranked each year using the 
narrow predation (W = 0.7) then the middle (0.3) or wide (0.3) definition. 

```{r}

##Anylise Abundance of the two main predators of guppies. Narrow view of predation 
#-----------------------------------------------------------------------------------

predatorsAbN <- fishData %>% 
	filter(species == "Hoplias malabaricus" | species == "Crenicichla frenata") %>%
	group_by(site, Year) %>%
	summarise(AbundanceSum = sum(AbundanceAll))%>%
	spread(Year, AbundanceSum)

predatorsAb <- data.frame(predatorsAbN)
predatorsAb[is.na(predatorsAb)] <- 0 
colnames(predatorsAb)[c(2:7)] <- c("2010", "2011", "2012", "2013", "2014", "2015")

predatorsAb

kendall.global(predatorsAb)

```

```{r}
##Anylise Abundance of the two main predators of guppies. middle view of predation 
#-----------------------------------------------------------------------------------

predatorsAbM <- fishData %>% 
	filter(species == "Hoplias malabaricus" | species == "Crenicichla frenata" | 
		species == "Gymnotus carapo"| species == "Anablepsoides hartii") %>%
	group_by(site, Year) %>%
	summarise(AbundanceSum = sum(AbundanceAll))%>%
	spread(Year, AbundanceSum)

mPredatorsAb <- data.frame(predatorsAbM)
mPredatorsAb[is.na(mPredatorsAb)] <- 0 
colnames(mPredatorsAb)[c(2:7)] <- c("2010", "2011", "2012", "2013", "2014", "2015")

mPredatorsAb

kendall.global(mPredatorsAb)

```

```{r}
##Anylise Abundance of the two main predators of guppies. middle view of predation 
#-----------------------------------------------------------------------------------

group12 <- c("Hoplias malabaricus", "Crenicichla frenata", "Gymnotus carapo", "Anablepsoides hartii",
			"Cichlasoma taenia", "Cichlasoma taenia", "Corynopoma riisei", "Roeboides dientonito", 
			"Agonostomus monticola", "Rhamdia quelen", "andinoacara pulcher", "Hemigrammus unilineatus")


predatorsAbW <- fishData %>% 
	filter(species %in% group12) %>%
	group_by(site, Year) %>%
	summarise(AbundanceSum = sum(AbundanceAll))%>%
	spread(Year, AbundanceSum)

wPredatorsAb <- data.frame(predatorsAbW)
wPredatorsAb[is.na(wPredatorsAb)] <- 0 
colnames(wPredatorsAb)[c(2:7)] <- c("2010", "2011", "2012", "2013", "2014", "2015")

wPredatorsAb

kendall.global(wPredatorsAb)

```