---
title: "Narrow Predation Tanglegram"
author: "Faith Jones"
date: "8 August 2017"
output: html_document
---

This scripts makes a tanglegram to compare the order of biomass vs abundance
defined sites, when you use the Narrow definition of predation (Hoplias malabaricus
and Crenicichla frenata. 

```{r, include=FALSE}
###Making a plot of how high pressure predation sites are when measured in 
#different levels of predation ABUNDANCE

setwd("C:\\Users\\faj\\Documents\\OneDrive for Business\\research\\FishPredation\\Data")

library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(Cairo)


#preparing data 

fishDataAll <- read.csv("Fish data June 2017.csv")
head(fishDataAll)
str(fishDataAll)
levels(fishDataAll$species)
selectMonths <- c("07", "08")# i am selecting out these months because then i can use the last timepoint 

#select data from only the July and Auguest, and remove first year 
SelectData <- fishDataAll %>% 
	separate(date, c("Day", "Month", "Year"), sep = "/") %>%
	filter(Year != 2010)%>%
	filter(Month %in% selectMonths)

fishData <- data.frame(SelectData)

fishData$AbundanceAll <- fishData$numbercaught + fishData$numberseen

#calculating percentage biomass so i can incude years with 0 abundance

fishData$TotBiomass <- (fishData$numbercaught + fishData$numberseen)* fishData$weight
TotBioSite<- fishData %>% 
	group_by(site, Year) %>%
	summarise(BiomasSiteSum = sum(TotBiomass, na.rm=TRUE))
siteBiomass <- data.frame(TotBioSite)


#Narrow Predation data
#-------------------------
predatorsAbN <- fishData %>% 
	filter(species == "Hoplias malabaricus" | species == "Crenicichla frenata")  %>%
	group_by(site, Year) %>%
	summarise(AbundanceSum = sum(AbundanceAll))

predatorsAb <- data.frame(predatorsAbN)
predatorsAb$Year <- as.numeric(predatorsAb$Year)

#add the total site biomass data, just to i can identify sites with no predators 
FishDataTotAb <- merge(siteBiomass, predatorsAb, by = c("site" ,"Year"),all=TRUE) # this makes sure i 
#know what years had no predators recoreded in 
FishDataTotAb$AbundanceSum[is.na(FishDataTotAb$AbundanceSum)] <- 0

Narrowa <- aggregate(FishDataTotAb$AbundanceSum, list(FishDataTotAb$site), mean, na.rm=TRUE)

orderNarrowa <- Narrowa[order(Narrowa$x),]
head(orderNarrowa)

orderNarrowa$predOrderNa <- c(1:nrow(orderNarrowa))
```

```{r, include=FALSE}
setwd("C:\\Users\\faj\\Documents\\OneDrive for Business\\research\\FishPredation\\Data")

library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(Cairo)


#preparing data 

fishDataAll <- read.csv("Fish data June 2017.csv")
head(fishDataAll)
str(fishDataAll)
levels(fishDataAll$species)
selectMonths <- c("07", "08")# i am selecting out these months because then i can use the last timepoint 


#select data from only the July and Auguest, and remove first year 
SelectData <- fishDataAll %>% 
	separate(date, c("Day", "Month", "Year"), sep = "/") %>%
	filter(Year != 2010)%>%
	filter(Month %in% selectMonths)

fishData <- data.frame(SelectData)

#calculate biomass
fishData$TotBiomass <- (fishData$numbercaught + fishData$numberseen)* fishData$weight


#calculating percentage biomass
TotBioSite<- fishData %>% 
	group_by(site, Year) %>%
	summarise(BiomasSiteSum = sum(TotBiomass, na.rm=TRUE))

siteBiomass <- data.frame(TotBioSite)

#Narrow Predation data
#-------------------------

#sum biomass per site and year
predatorsBioN <- fishData %>% 
	filter(species == "Hoplias malabaricus" | species == "Crenicichla frenata") %>%
	group_by(site, Year) %>%
	summarise(BiomassSum = sum(TotBiomass))

predatorsBio <- data.frame(predatorsBioN)
predatorsBio$Year <- as.numeric(predatorsBio$Year)
siteBiomass$Year <- as.numeric(siteBiomass$Year)

FishDataTot <- merge(siteBiomass, predatorsBio, by = c("site" ,"Year"),all=TRUE) # this makes sure i 
#know what years had no predators recoreded in 
head(FishDataTot)
FishDataTot$BiomassSum[is.na(FishDataTot$BiomassSum)] <- 0

FishDataTot$PropMass <- FishDataTot$BiomassSum / FishDataTot$BiomasSiteSum

Narrowb <- aggregate(FishDataTot$PropMass, list(FishDataTot$site), mean, na.rm=TRUE)

orderNarrowb <- Narrowb[order(Narrowb$x),]
head(orderNarrowb)

orderNarrowb$predOrderNb <- c(1:nrow(orderNarrowb))

```

```{r, include=FALSE}

bothNarrow <- merge(orderNarrowb, orderNarrowa, by = "Group.1")

```

```{R}
Cairo(file="C:\\Users\\faj\\Documents\\OneDrive for Business\\research\\bioTIME\\users\\Faith\\TriniFishPredation\\narrowAB_tangle.png",
      type="png",
      units="in", 
      width=6,
      height=6,
      pointsize=12,
      dpi=100)

plotSetup <- data.frame(cbind(c(1:17),c(20:60))) # data to plot onto emptyp plot
plot(x = plotSetup$X2, y = plotSetup$X1, col="white", axes=FALSE , ylab = " ", xlab = "  ")

#plot arrows
arrows(x0 = 36, y0 = bothNarrow$predOrderNb, x1 = 48, y1 = bothNarrow$predOrderNa, length = 0.001)


#plotting text 
text(x = 54, y = bothNarrow$predOrderNa, labels = bothNarrow$Group.1)
text(x = 30, y = bothNarrow$predOrderNb, labels = bothNarrow$Group.1)


text(x = 30, y = 17, labels = "Biomass", cex = 1.5)
text(x = 54, y = 17, labels = "Abundance", cex = 1.5)


dev.off()

```
